name: Commitlint, Lint, Type Check, Test & Build

on:
  pull_request:
    branches:
      - main
      - develop
      - releases/**

jobs:
  commitlint-lint-typecheck-test-build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_UNCHAINED_ETHEREUM_HTTP_URL: https://dev-api.ethereum.shapeshift.com
      REACT_APP_UNCHAINED_ETHEREUM_WS_URL: wss://dev-api.ethereum.shapeshift.com
      REACT_APP_UNCHAINED_BITCOIN_HTTP_URL: https://dev-api.bitcoin.shapeshift.com
      REACT_APP_UNCHAINED_BITCOIN_WS_URL: wss://dev-api.bitcoin.shapeshift.com
      REACT_APP_PORTIS_DAPP_ID: 8609e6a8-e0dc-45e6-a0ad-edde63a4cdda
      REACT_APP_ETHEREUM_NODE_URL: https://mainnet.infura.io/v3/d734c7eebcdf400185d7eb67322a7e57
      REACT_APP_FEATURE_COSMOS_INVESTOR: false
      REACT_APP_GEM_COINIFY_SUPPORTED_COINS: https://api.gem.co/institutions/coinify/supported_currencies
      REACT_APP_GEM_WYRE_SUPPORTED_COINS: https://api.gem.co/institutions/wyre/supported_currencies
      REACT_APP_GEM_ASSET_LOGO: https://gem-widgets-assets.s3-us-west-2.amazonaws.com/currencies/crypto/
      REACT_APP_GEM_ENV: production
      REACT_APP_GEM_API_KEY: 17baca45f492df6b8974d4f832a659c92644acafea3284cfb0d52550dd3bde1a
      REACT_APP_GEM_URL: https://onramp.gem.co
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install
        run: yarn install --frozen-lockfile
      # needs to run after install
      - name: Commitlint PR title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: printf '%s' "$TITLE" | npx commitlint
      - name: Lint
        run: yarn lint
      - name: Type check
        run: yarn type-check
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
